name: base_template_bloc
description: "Base template flutter using clean architecture & bloc state managerment"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #state managerment
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  #rxdart
  rxdart: ^0.27.7

  #comparing objetcs
  equatable: ^2.0.5

  #service locater
  get_it: ^7.6.4

  #networking
  dio: ^5.3.3

  #localization & language
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #google fonts
  google_fonts: ^4.0.3

  #shared preferences
  shared_preferences: ^2.0.15

  #routes
  auto_route: ^7.2.0

  #image
  cached_network_image: ^3.3.1

  #log bloc
  bloc_concurrency: ^0.2.5

  #animation
  lottie: ^3.1.2

  #import file
  file_picker: ^8.0.6

  #parse gpx file
  gpx: ^2.2.2

  #show map
  flutter_map: ^7.0.2

  #coordinates
  latlong2: ^0.9.1

  #vibration
  vibration: ^1.9.0

  #create folder save file
  path_provider: ^2.1.3

  #xml
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

  flutter_lints: ^3.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

